name: Build and Deploy

on:
  push:
    branches:
      - develop
  release:
    types:
      - created

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        yarn
    
    - name: Build the app
      run: |
        yarn generate
    
    - name: Deploy to ECR and Kubernetes
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Dockerfile.lean
        build-args: BUILDKIT_INLINE_CACHE=1
        tags: ${{ github.repository }}:${{ github.sha }}
    
    - name: Push to ECR
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Push to ECR repository
      run: |
        docker push ${{ github.repository }}:${{ github.sha }}
    
    - name: Rollout Kubernetes deployment
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.K8S_DEV_CONFIG }}
        version: 1.19.8
        args: rollout restart deployment/$DEPLOYMENT_NAME
